apiVersion: apps/v1
kind: Deployment
metadata:
  name: SampleApp
  labels:
    app: sampleApp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleApp
  template:
    metadata:
      labels:
        app: sampleApp
    spec:
      containers:
      - name: SampleApp
        image: msvsdocker/sample-app:latest
        ports:
        - containerPort:8080
        - containerPort:8081
      imagePullSecrets:
      - name: dockerhub-secret