apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleApp
  labels:
    app: sampleApp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleApp
  template:
    metadata:
      labels:
        app: sampleApp
    spec:
      containers:
      - name: my-sample-app
        image: msvsdocker/my-sample-app:latest
        ports:
        - containerPort: 8080
        - containerPort: 8081
      imagePullSecrets:
      - name: dockerhub-secret