name: CI/CD Pipeline

on:
    push:
        branches:
            - main
jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest

        steps:
        #Step1: Checkout the repository    
        - name: Checkout Code
          uses: actions/checkout@v3 

         # List the directory contents to debug the path issue
        - name: List directory contents
          run: |
            ls -alh 

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PAT}}
        
        - name: Build and push docker image
          run: |
            docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/my-sample-app:${{ github.sha }} -f Dockerfile . --push


    deploy:
        name: Deploy to AWS EKS
        needs: build
        runs-on: ubuntu-latest

        steps:
        #Step1: Checkout the repositoty
        - name: Checkout the code
          uses: actions/checkout@v3

        #Step2: Configure AWS Credentials
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: us-east-1
        - name: Update kubeconfig for EKS
          run: |
            aws eks update-kubeconfig --region us-east-1 --name new-eksCluster
 

        - name: Create kubernetes Secret for Docker Hub
          run: |
            kubectl create secret docker-registry dockerhub-secret \
              --docker-username="${{ secrets.DOCKER_USERNAME}}" \
              --docker-password ="${{ secrets.DOCKER_PAT}}" \
              --docker-email ="${{ secrets.DOCKER_EMAIL}}"\
              -dry-run=client -0 yaml | kubectl apply -f -

        #Step4: Deploy to Kubernets
        - name: Deploy to EKS
          run: |
            kubectl apply -f k8s-deployment.yaml
            kubectl apply -f service.yaml    

    
            
        